homepage/urls.py
from django.urls import path, register_converter

from . import converters, views

app_name = 'homepage'

register_converter(converters.NegativeIntConverter, 'negint')

urlpatterns = [
    path('', views.index, name='index'),
    path('riwayat/', views.riwayat, name='riwayat'),
    path('time/<negint:diff>/', views.waktu, name='waktu'),
    path('time/', views.waktu, name='waktu'),
]

homepage2/urls.py
from django.urls import path
from . import views

app_name = 'homepage2'

urlpatterns = [
    path('', views.indexdua, name='indexdua'),
]

kuliah/urls.py
from django.urls import path
from . import views

app_name = 'kuliah'

urlpatterns = [
    path('add/', views.formMatkul, name='formMatkul'),
    path('result/', views.resultMatkul, name='resultMatkul'),
    path(r'^matkuldetails/(?P<pkTarget>)/$', views.detailsMatkul, name='detailsMatkul'),
    path(r'^result/(?P<pkTarget>)/$', views.deleteMatkul, name='deleteMatkul'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('homepage2/', include('homepage2.urls')),
    path('jadwal/', include('kuliah.urls')),
    path('kegiatan/', include('story6.urls')),
]

story6/urls.py
from django.urls import path
from .views import *
from django.conf.urls import url

app_name = 'story6'

urlpatterns = [
    path('', kegiatan, name='peserta'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage2/models.py
from django.db import models

# Create your models here.

kuliah/models.py
from django.db import models
from django.forms import ModelForm
from django.core.validators import MinValueValidator

class Jadwal(models.Model):
    nama = models.CharField(max_length=50)
    dosen = models.CharField(max_length=50)
    sks = models.IntegerField(validators=[MinValueValidator(0)])
    deskripsi = models.CharField(max_length=50)
    semester = models.CharField(max_length=20)
    kelas = models.CharField(max_length=10)

class Tugas(models.Model):
    tugas = models.CharField(max_length=50)
    deadline = models.DateField()

class MatkulForm(ModelForm):
    class Meta:
        model = Jadwal
        fields = ['nama', 'dosen', 'sks', 'deskripsi', 'semester', 'kelas']

story6/models.py
from django.db import models
from django.forms import ModelForm
from django import forms

class Kegiatan(models.Model):
    nama = models.CharField(max_length=30)

    def __str__(self):
        return self.nama


class DaftarPeserta(models.Model):
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)
    peserta = models.CharField(max_length=50)

    def __str__(self):
        return self.peserta + " ikut " + self.kegiatan.nama

class KegiatanForm(ModelForm):
    class Meta:
        model = DaftarPeserta
        fields = '__all__'
        widgets = {
            'peserta': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'kegiatan': forms.Select(attrs={
                'class': 'form-control'
            }),
        }



# Create your models here.

homepage/views.py
from django.shortcuts import render
import datetime

def index(request):
    return render(request, 'home.html')

def riwayat(request):
    return render(request, 'riwayat.html')

def waktu(request, diff = 0):
    return render(request, 'time.html', context={'value':datetime.datetime.now() + datetime.timedelta(hours=diff)})

# Create your views here.

homepage2/views.py
from django.shortcuts import render

def indexdua(request):
    return render(request, 'story1.html')

# Create your views here.

kuliah/views.py
from django.shortcuts import render, redirect
import json
from django.core.serializers import serialize
from .models import Jadwal, MatkulForm

def formMatkul(request):
    
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('kuliah:formMatkul')

    else:
        form = MatkulForm()

    return render(request, 'forms.html', {'form': form})

def resultMatkul(request):

    data = Jadwal.objects.all()
    x_data = json.loads(serialize('json', data))

    return render(request, 'result.html', {'data':x_data})

def detailsMatkul(request, pkTarget):
    details = Jadwal.objects.filter(pk=pkTarget)
    detailsTarget = json.loads(serialize('json', details))

    return render(request, 'details.html', {'details':detailsTarget})

def deleteMatkul(request, pkTarget):
    target = Jadwal.objects.filter(pk=pkTarget)
    target.delete()

    x_data = json.loads(serialize('json', Jadwal.objects.all()))

    return render(request, 'result.html', {'data':x_data})

story6/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import *

def kegiatan(request):
    daftarKegiatan = Kegiatan.objects.all()
    peserta = DaftarPeserta.objects.all()
    form = KegiatanForm(request.POST or None)
    if form.is_valid():
        form.save()
    return render(request, 'kegiatan.html', {'form': form, 'obj':daftarKegiatan, 'peserta':peserta})


# Create your views here.

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Story 3 Rafli Bangsawan</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <header><h1>B a n g s a w a n</header>
          {% include 'includes/_navbar.html' %}
            <br>
          {% block body %}

          {% endblock %}
        <footer>
            <ul>
                <li><a href="www.linkedin.com/raflibangsawan"><img src="{% static '58e91afdeb97430e81906504.png' %}"></a></li>
                <li><a href="www.twitter.com/raflibangsawan0"><img src="{% static '580b57fcd9996e24bc43c53e.png' %}"></a></li>
                <li><a href="www.instagram.com/raflibangsawan"><img src="{% static '580b57fcd9996e24bc43c521.png' %}"></a></li>
            </ul>
        </footer>
    </body>
</html>

homepage/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="headline" align="center">
    <p><b>T E N T A N G</b></p>
</div>
<img src="{% static 'mantap.png' %}" style="width: 100%; height:auto">
<div class="profile" align="center" style="width: 100%; height: auto; padding: 0 30% 0 30%;">
    <img src="{% static 'line_268100084708497.jpg' %}" style="width: 300px; height: 300px; margin-top: 20%;">
    <h1 style="margin-top: 3%;">Hai, Saya Awan!</h1>
    <p style="margin-top: 5%; text-align: justify; padding-bottom: 20%;">Merupakan mahasiswa Ilmu Komputer Universitas Indonesia. Lahir tanggal 27 Desember 2000 di Bandar Lampung. 
    Selain di dunia programming, juga memiliki ketertarikan dalam musik. Lulus pada tahun 2019 dari SMAN 2 Bandar Lampung.
    Mempunyai harapan untuk dapat berperan dalam banyak aspek terutama dalam bidang IT.</p>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
Gallery saya
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel"></h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'bicf.jpg' %}" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'mantap.png' %}" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static '4pilar.jpg' %}" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

homepage/templates/includes/_navbar.html
<!DOCTYPE html>
<html>
<head></head>
<body>
<nav class="navbar navbar-expand-sm bg-light justify-content-center">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:index' %}">Tentang</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:riwayat' %}">Riwayat</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage2:indexdua' %}">Story 1</a>
        </li>
    </ul>
</nav>
</body>
</html>

homepage/templates/riwayat.html
{% extends 'base.html' %} 
<!DOCTYPE html>
{% load static %}
{% block body %}
<div class="headline" align="center">
  <p><b>R I W A Y A T</b></p>
</div>
<div class="profil1" align="center" style="width: 100%; height: auto;">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="{% static 'bicf.jpg' %}" alt="First slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>Bali International Choir Festival</h5>
            <p>Mendapat 3 Gold Medal di 2 Kategori</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'mantap.png' %}" alt="Second slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>Festival Lomba Seni Siswa Nasional 2018</h5>
            <p>Meraih medali perak di cabang gitar solo</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static '4pilar.jpg' %}" alt="Third slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>LCC 4 Pilar Kebangsaan MPR RI 2018</h5>
            <p>Mendapat Juara 2 Provinsi</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</div>
{% endblock %}

homepage/templates/time.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body %}
<div class="display-3" style="text-align: center; color: blue;">{{ value|time:"H:i" }}</div>
{% endblock %}

homepage2/templates/story1.html
<!DOCTYPE html>

<html>
    <head>
        <title>
            Story 1 Euy!
        </title>
        <style>
            body {
                background: rgb(17, 67, 73);
                font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
                color: white;
                margin: 0;
                padding: 0;
            }
            header {
                color: rgb(0, 255, 234);
                font-size: 45pt;
                background: rgb(22, 22, 22);
                padding: 30pt;
            }
            li {
                display: inline-block;
                margin: 20px;
            }
            ul {
                margin: 0;
                padding: 0;
                font-size: 15pt;
                list-style-type: none;
            }
            section {
                padding: 30pt;
                font-size: 10px;
            }
            footer {
                background: rgb(22, 22, 22);
                padding: 20pt;
            }
            div {
                padding: 20px;
                font-size: 10px;
            }
            table {
                font-size: 40px;
                margin: 10px;
                border-spacing: 30px;
            }
            img {
                float: left;
                border-radius: 20px;
                width: 250px;
                margin: 40px 20px 0 0;
            }
            .column {
                float: left;
                width: 150px;
                padding: 0px;
            }
            .row::after {
                content: "";
                clear: both;
                display: table;
            }
        </style>

    </head>
    <body>
        <header>
            <b>Story 1 Euy!</b>
        </header>
        <section><font size="30">
            <b>Profil Singkat</b>
        </font>
        <div>
            <img src="https://maung.id/static/71c03e5a4281f4d1547ea79eeb45c414/9f583/AU43.jpg">
            <table><col width="300">
                <tr>
                    <td>Nama</td>
                    <td>Rafli Bangsawan</td>
                </tr>
                <tr>
                    <td>Tanggal Lahir</td>
                    <td>27 Desember 2000</td>
                </tr>
                <tr>
                    <td>Jurusan</td>
                    <td>Ilmu Komputer</td>
                </tr>
                <tr>
                    <td>Angkatan</td>
                    <td>2019</td>
                </tr>
                <tr>
                    <td>NPM</td>
                    <td>1906398414</td>
                </tr>
                <tr>
                    <td>Hobi</td>
                    <td>Bermain gitar</td>
                </tr>
            </table>
        </div>
        <div>
            <font size="30"><b>Deskripsi Tentang Saya</b></font>
            <p><font style="font-size: 30px; line-height: 45px;">Merupakan mahasiswa semester 2 Fakultas Ilmu Komputer Universitas Indonesia.
            Mengambil kuliah jurusan ilmu komputer dengan harapan dapat berperan dalam kemajuan teknologi informasi.
            Bertekad untuk melanjutkan kuliah di bidang ilmu komputer sejak SMA meskipun tidak mempunyai pengalaman dalam
            bidang komputer. Mengikuti berbagai jenis lomba akademis maupun non-akademis semasa SMA dan pada tahun 2018 berhasil meraih juara 2
            FLS2N Nasional bidang gitar tunggal.</font></p>
        </div>
        <div>
            <font size="30"><b>Riwayat Pendidikan</b></font>
            <table><col width="300">
                <tr>
                    <td>2019 - sekarang</td>
                    <td>Universitas Indonesia</td>
                </tr>
                <tr>
                    <td>2016 - 2019</td>
                    <td>SMAN 2 Bandar Lampung</td>
                </tr>
                <tr>
                    <td>2013 - 2016</td>
                    <td>SMPN 2 Bandar Lampung</td>
                </tr>
                <tr>
                    <td>2007 - 2013</td>
                    <td>SD Al-Kautsar</td>
                </tr>
            </table>
        </div>
        </section>
        <footer>
            <font style="font-size: 30px;margin: 0 0 0 20px;"><b>Kontak Saya</b></font>
            <div class="row">
                <div class="column">
                    <a href="https://www.instagram.com/raflibangsawan/">
                        <img src="https://www.freepnglogos.com/uploads/logo-ig-png/logo-ig-instagram-new-logo-vector-download-13.png" alt="Instagram" style="width:100px">
                    </a>
                    </div>
                <div class="column">
                    <a href="https://www.twitter.com/raflibangsawann">
                        <img src="https://seeklogo.com/images/T/twitter-icon-square-logo-108D17D373-seeklogo.com.png" alt="Twitter" style="width:100px">
                    </a>
                    </div>

              </div>
        </footer>
    </body>
</html>

kuliah/templates/bases.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Story 3 Rafli Bangsawan</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <header><h1>B a n g s a w a n</header>
          {% include 'includes/_navbarJadwal.html' %}
            <br>
          {% block body %}

          {% endblock %}
        
    </body>
</html>

kuliah/templates/details.html
{% extends 'bases.html' %}
{% load static %}
{% block body %}

<table style="text-align: center;">
        <tr>
            <th>Matkul</th>
            <th>Dosen</th>
            <th>Jumlah SKS</th>
            <th>Semester</th>
            <th>Kelas</th>
            <th>Deskripsi</th>
        </tr>
        {% for hasil in details %}
        
        <tr>
            <td><a href="{% url 'kuliah:detailsMatkul' pkTarget=hasil.pk  %}">{{ hasil.fields.nama }}</a></td>
            <td>{{ hasil.fields.dosen }}</td>
            <td>{{ hasil.fields.sks }}</td>
            <td>{{ hasil.fields.semester }}</td>
            <td>{{ hasil.fields.kelas }}</td>
            <td>{{ hasil.fields.deskripsi }}</td>
            <br>
        </tr>
        {% endfor %}

    </table>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

{% endblock %}

kuliah/templates/forms.html
{% extends 'bases.html' %}
{% load static %}
{% block body %}
    <h1>Jadwal Kuliah</h1>
    <form method="POST" action="#">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">SUBMIT</button>
    </form>
{% endblock %}

kuliah/templates/includes/_navbarJadwal.html
<!DOCTYPE html>
<html>
<head></head>
<body>
<nav class="navbar navbar-expand-sm bg-light justify-content-center">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kuliah:formMatkul' %}">Form</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kuliah:resultMatkul' %}">Result</a>
        </li>
    </ul>
</nav>
</body>
</html>

kuliah/templates/result.html
{% extends 'bases.html' %}
{% load static %}
{% block body %}

    <table style="text-align: center;">
        <tr>
            <th>Matkul</th>
            <th>Dosen</th>
            <th>Jumlah SKS</th>
            <th>Semester</th>
            <th>Kelas</th>
            <th>Deskripsi</th>
        </tr>
        {% for hasil in details %}
        
        <tr>
            <td><a href="{% url 'kuliah:detailsMatkul' pkTarget=hasil.pk  %}">{{ hasil.fields.nama }}</a></td>
            <td>{{ hasil.fields.dosen }}</td>
            <td>{{ hasil.fields.sks }}</td>
            <td>{{ hasil.fields.semester }}</td>
            <td>{{ hasil.fields.kelas }}</td>
            <td>{{ hasil.fields.deskripsi }}</td>
            <td><a href="{% url 'matkul:deleteMatkul' pkTarget=hasil.pk %}">DELETE</a></td>
            <br>
        </tr>
        {% endfor %}

    </table>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>
{% endblock %}

story6/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Story 3 Rafli Bangsawan</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <header><h1>B a n g s a w a n</header>
          {% include 'includes/_navbar.html' %}
            <br>
          {% block body %}

          {% endblock %}
        <footer>
            <ul>
                <li><a href="www.linkedin.com/raflibangsawan"><img src="{% static '58e91afdeb97430e81906504.png' %}"></a></li>
                <li><a href="www.twitter.com/raflibangsawan0"><img src="{% static '580b57fcd9996e24bc43c53e.png' %}"></a></li>
                <li><a href="www.instagram.com/raflibangsawan"><img src="{% static '580b57fcd9996e24bc43c521.png' %}"></a></li>
            </ul>
        </footer>
    </body>
</html>

story6/templates/includes/_navbar.html
<!DOCTYPE html>
<html>
<head></head>
<body>
<nav class="navbar navbar-expand-sm bg-light justify-content-center">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:index' %}">Tentang</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:riwayat' %}">Riwayat</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage2:indexdua' %}">Story 1</a>
        </li>
    </ul>
</nav>
</body>
</html>

story6/templates/kegiatan.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<h1>Daftar Kegiatan</h1>
<div class="col-sm-4">
  {% for object in obj %}
<strong>{{ object.nama }}</strong>
{% for orang in peserta %}
{% if orang.kegiatan == object %}
<li>
  <ul>{{ orang.peserta }}</ul>
</li>
{% endif %}
{% endfor %}
{% endfor %}
 
</div>
    
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
  Ikut Kegiatan
</button>

<!-- Modal -->
<form method="POST">
  {% csrf_token %}
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Gabung {{ object.nama }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      Silahkan Pilih Kegiatan di Bawah <br>
        {{ form.as_p }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </div>
  </div>
</div>
</form>
{% endblock %}